### ISSUE TITLE
Ghost layers are not created

### ISSUE THREAD

**Issue by nikitink** [INMOST-DEV/INMOST#13]
Examples (unchanged github version) give different results when solved using 1 and 2 processors:
$ cd examples/FVDiscr
$ mpirun -np 2 ../GridGen/GridGen 4 32 32 32
Cubic Grid: 32 x 32 x 32
Processors: 2
Mesh generator time: 1.53127
Save to file "grid.pvtk" time: 0.09009
$ ../GridGen/GridGen 4 32 32 32
Cubic Grid: 32 x 32 x 32
Processors: 1
Mesh generator time: 2.60488
Save to file "grid.vtk" time: 0.167997
$ mpirun -np 2 ./FVDiscr grid.pvtk 
Processors: 2
...
Solve system: 1.6159514e-05 | 1e-05
err_C  = 0.00229488
err_L2 = 0.000640307
...
$ mpirun -np 1 ./FVDiscr grid.pvtk 
Processors: 1
...
Solve system: 2.72933175848 | 1e-05
err_C  = 0.000799091
err_L2 = 0.000283771
...
$ ./FVDiscr grid.vtk 
Processors: 1
...
Solve system: 2.72284175848 | 1e-05
err_C  = 0.000799091
err_L2 = 0.000283771
...
Using multiple proc gives the same result as presented on https://github.com/INMOST-DEV/INMOST/wiki/1710-FVDiscr-Example , yet it is not correct and is different from 1 proc.

If one switches func and func_rhs from FVDiscr/main.cpp in the following way:
Storage::real func(Storage::real x[3], Storage::real tmp) {
	return 0;
}
Storage::real func_rhs(Storage::real x[3], Storage::real tmp) {
	if (x[0] < 0.5) return 1;
	return 0;
}
The results for 16x16x16 are (left - serial, right - parallel with 2 proc.):
![fvdiscr_paral](https://cloud.githubusercontent.com/assets/11333024/7950287/ff7a2ac0-09a0-11e5-8ff6-d6875ccd44c7.png)

And for 32x32x32 the FVDiscr fails to solve at all and stucks on the 1st iter:
$ mpirun -np 2 ./FVDiscr grid.pvtk 
Processors: 2
...
iter   1 resid  9.49888e-05 | 1e-05

It seems that ResolveShared() doesn't do the job correctly. Both processors have their unpack_real of zero length where it is supposed to be compared with pack_real.

**Comment by kirill-terekhov** [comment]
Since you already look into the code, I recommend you taking a look on how bounding boxes are intersected in ResolveShared. Most likely there is an incorrect floating point comparison that prevents identification of intersection of parts of the mesh. You can check whether disabling the comparison resolves your problem. You should look into the place where variable bbox is compared to variable bboxs.

**Comment by nikitink** [comment]
This is not the case.
I've fixed tiny bug which resulted in wrong syncing of numbers of nodes to be compared. Now they are compared properly, and the correct intersections are found. But the resulting grid still lacks ghost layers as far as I can see, and the examples still stuck/give wrong results.

**Comment by kirill-terekhov** [comment]
Well it is not small since it leads to an issue. I've probably missed that during one of the big updates.

The second problem is in call to ComposeHandle function in ResolveShared.
After bitwise shift on argument of type char it assumes that the argument is integer and uses incorrect ComposeHandle function. It would be nice if you upload a fix to this as well.

This will fix ResolveShared. But there seems to be another problem in ComputeSharedSkinSet that is most likely also not big but nasty.

I can share with you one of the mechanisms that can help debug inmost in this and future problems:
1) Go to inmost_common.h and uncomment USE_PARALLEL_WRITE_TIME and recompile inmost. Then during execution each processor will write time_*.xml file into your folder.
2) Copy style.xsl file from examples/Solver to the folder where *.xml files were generated. This file will help interpret xml contents of generated files. You can try to run FVDiscr for example and see what's inside. Inside you should get function names, execution times and some intermediate contents. By clicking on function name you can fold and unfold the contents in it (in internet explorer it asks you to allow active content before you can do that).
3) At the top of mesh_parallel.cpp there are macroses that help output content to xml files. You can look through some functions to get the sense on how to use them.
4) In case the program crashes you should close xml tags in generated xml files before you open them in browser.

**Comment by kirill-terekhov** [comment]
The other problem comes from UnpackSkin function that assumes that the size of the message will always be equal to 2.

**Comment by nikitink** [comment]
Well, the first fix (ComposeHandle) seems to solve the problem of ghost layers not being created (at least NumberOfCells() shows the correct number now), BUT the FVDiscr solver now fails to converge:
$ mpirun -np 4 ./FVDiscr grid.pvtk 
...
Solve system: 0.9847035e+76 | 1e-05
err_C  = 3.0467e+76
err_L2 = 1.40134e+75
...
Haven't found yet what it is caused by.

If I apply the 2nd fix (size != 2 in UnpackSkin) there's no difference on the first call of ExchangeGhost (all sizes in UnpackSkin = 2) but on the second call I get sizes = 4 and
GridGen: /home/nikitink/Work/INMOST/mesh_parallel.cpp:1839: INMOST::Mesh::proc_elements INMOST::Mesh::ComputeSharedSkinSet(INMOST::ElementType): Assertion `skin_data.size()/2 == 2' failed.
which is assumed to track invalid grid topology.

Did you manage to make it work on your INMOST version?

**Comment by kirill-terekhov** [comment]
Yes for me it works.

Forgot about the solver.
In solver_bcgsl.hpp there is a call to Integrate with parameter tau.
The second parameter there should be not size*size+size but (l+2)*(l+1).

**Comment by nikitink** [comment]
Ok, this solves the INNER_ILU2 problem indeed (and PETSc didn't fail as I've just checked).

But do you get the same solutions from FVDiscr for 1 and 2 processors?
I don't. Now it can flow through the ghost cells but much weaker than for the single-core grid and the solutions are different. May be you can upload the fixed code if your version works well?

**Comment by kirill-terekhov** [comment]
I always get the same solution for 1 and 2 processors. 
But for 4 processors I get the same solution randomly from time to time. 
The issue is again in the fact that small part of ghosting is not done correctly but for some reason just sometimes.

**Comment by kirill-terekhov** [comment]
Please check that last commit resolves your problems.
